[project]
name = "classtrack"
version = "0.1.0"
description = "ClassTrack - a class tracking application"
readme = "README.md"
authors = [
    { name = "Hanny Abubakar", email = "hanny0568@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "django>=6.0.7",
]

[dependency-groups]
dev = [
    "ruff>=0.16.1",
]

[tool.ruff.lint]
ignore = ["RUF012"]

[tool.ruff.lint.per-file-ignores]
"**/migrations/*.py" = ["I001"]
